config/routes.rb
Rails.application.routes.draw do
  devise_for :pastors
  root to: 'home#index'

  resources :home, :only => [:index]
  
  resources :attendee, :only => [:index, :create, :show, :delete] do
    collection do
      get :authorise_fb    
    end
  end

  get 'fb_oauth_callback', {
    :to => 'attendee#fb_oauth_callback',
    :as => :fb_oauth_callback
  }

  resources :church, :only => [:index, :create, :show, :delete]
  resources :event, :only => [:index, :create, :new, :show, :edit, :update, :delete]
  resources :event_attendee, :only => [:create]
  resources :search, :only => [:index]
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
	has_many :events, :through => :event_attendees
	has_many :event_attendees
end

app/models/church.rb
class Church < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

	has_many :events
	has_one :pastor
	validate :name, presence: true
	geocoded_by :address, :latitude => :lat, :longitude => :lng
	after_validation :geocode 

	def self.churches_list
		doc = Nokogiri::HTML(open("http://www.adventistchurches.org.uk/churches.php?Field=SEC%20(London)"))
		# find out how to gsub on mapped objects
		
		doc.css("tr>td>p").each do |c|c.text
			@name = c.children[0].text.chomp.strip.gsub(":", "")
			if c.children[1] != nil
				@address = c.children[1].text.chomp.strip.gsub(".  (See", "")
			end
			if c.children[5] != nil
				@phone = c.children[5].text.chomp.strip.gsub(") Phone: ", "")
			end
			# if c.children[??] != nil
			# 	@email = ""
			# end
			church = Church.new
			church.name = @name
			church.address = @address 
			church.phone = @phone
			church.save!
		end
	end


end

app/models/church_events.rb
class ChurchEvents < ActiveRecord::Base
	 belongs_to :churches 
	 belongs_to :events
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :church
	has_many :attendee, :through => :event_attendees
	has_many :event_attendees

	geocoded_by :address, :latitude => :lat, :longitude => :lng
	after_validation :geocode

	validates :church_id, presence: true
end

app/models/event_attendee.rb
class EventAttendee < ActiveRecord::Base
	belongs_to :attendee
	belongs_to :event

end

app/models/pastor.rb
class Pastor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :churches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :church_id
  end
end

app/controllers/attendee_controller.rb
class AttendeeController < ApplicationController



	def index
		
	end

	def show
		@attendee = Attendee.find(params[:id])
		@events = Event.all
		# layout :determine_layout
	end
		
	def authorise_fb
		redirect_to fb_oauth_client.auth_code.authorize_url(
			:redirect_uri => fb_oauth_callback_url,
			:scope => %w(email user_friends).join(",")
		)
		# binding.pry
	end

	def fb_oauth_callback
		access_token = fb_oauth_client.auth_code.get_token(
			params[:code],
			:redirect_uri => fb_oauth_callback_url,
			:parse => :query
		)
		# binding.pry


		 attendee_info = JSON(access_token.get('https://graph.facebook.com/me').body).symbolize_keys

		@attendee = Attendee.find_or_create_by!(
			:fb_id => attendee_info[:id],
			:name => attendee_info[:name], 
		)

		@attendee.access_token = access_token.token
		@attendee.save!

		session[:attendee_id] = @attendee.id

		redirect_to attendee_path(@attendee)
	end

	private
	def fb_oauth_client
	  @fb_oauth_client ||= OAuth2::Client.new(
	     FindA::Application.config.fb_id,
	     FindA::Application.config.fb_secret,
	     :site => "https://graph.facebook.com",
	     :token_url => '/oauth/access_token'
	  )
	end	

	# def determine_layout
 #    current_attendee ? "private" : "public"
 #  end


end

app/controllers/church_controller.rb
class ChurchController < ApplicationController

	def index
		@church = Church.all
	end

	def show
		@church = Church.find(params[:id])
		@event = Event.create!
		@events = Event.all
	end

	# private
	# def allowed_params
	# 	params.require(:c).permit(:name, :address, :start_time, :end_time, :type, :description, :date)
	# end


end

app/controllers/event_attendee_controller.rb
class EventAttendeeController < ApplicationController

	def create
		@attendence = EventAttendee.new
		@attendence.attendee_id = params[:attendee_id]
		@attendence.event_id = params[:event_id]
		@attendence.save!
	end
end

app/controllers/event_controller.rb
class EventController < ApplicationController

	def index
		@events = Event.all

	end

	def show

	end

	def create
		@event = Event.new(allowed_params)
		if @event.save
			respond_to do |format|
				format.html {redirect_to event_index_path, :notice => "Your event has been saved"}
				format.js 
			end
		else
			render :new
		end
	end

	def new
		@event = Event.new
	end


	def edit
		@event = Event.find_or_create_by!(name: event.name)
	end

private
def allowed_params
	params.require(:event).permit(:name, :address, :start_time, :end_time, :event_type, :description, :date, :church_id)
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/pastor_controller.rb
class PastorController < ApplicationController

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def index
		@search_ch = Church.near(params[:location])
		@search_ev = Event.near(params[:location])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendee_helper.rb
module AttendeeHelper
end

app/helpers/church_helper.rb
module ChurchHelper
end

app/helpers/event_attendee_helper.rb
module EventAttendeeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pastor_helper.rb
module PastorHelper
end

app/views/attendee/index.html.erb
<!DOCTYPE html>
<html lang="en">

    <head>
      <meta charset="utf-8">
      <title>findA</title>
      
    </head>

    <body>
        <h1> findA </h1> 
        <p> Your app for finding your closests Adventist churches and events. </p> 

        <nav id="navigation">
            <%= link_to "Login with Facebook", authorise_fb_attendee_index_path %>
        </nav>



        <section id="footer">
        </section>


    </body>

</html>

app/views/attendee/show.html.erb
<main class="show">
	
	<h2>Hi <%= @attendee.name %></h2>

	<div id="profile_content">

	<div id='search_field'>
	<%= form_tag(search_index_path, :method => :get) do %>
		<div class="search_button">
	 		<%= label_tag(:location, "Search:") %>
		</div>
	  <%= text_field_tag(:location) %>
	  <%= submit_tag("Search") %>
	<% end %>
	</div>
		
		
		<div id="all_events">
		<h3> All events </h3>
			<ul id="events">
			<% @events.each do |event| %>
				<li class="event" data-latitude="<%=event.lat%>" data-longitude="<%=event.lng%>">
					<%= event.name %> <%= event.event_type %> <%= event.date %> <%= event.church.name %>
					<%= button_to "Attend", event_attendee_index_path(event_id: event.id, attendee_id: session[:attendee_id]), id: "attend", remote: true, data:{disable_with: "Attending"} %>
				</li> </br>
			<% end %>
			</ul>
			</div>
		
		</div>


		<div id="my_events">
			<h3> My Events </h3>
			<ul id="my_event_list">
			</ul>
		</div>

		<div class="clear"></div>
	</div>

</main>

app/views/church/show.html.erb
<main class="show">
	<h2> <%= @church.name%> profile </h2>

	<div id="profile_content">
		


		<%= link_to 'Events', event_index_path %>
		<%= link_to 'Create Event', new_event_path, :remote => true, :id => 'create_event' %>

		<div id="event_create"> 
		</div>

		<div id="map"> </div>

		<ul>
<% @events.each do |event| %>
<li class="events" data-latitude="<%=event.lat%>" data-longitude="<%=event.lng%>">


	<%= event.name %> <%= event.event_type %> <%= event.date %>
	
	<%=link_to 'Edit', edit_event_path(:id)%>
	
	<%=link_to 'Show', event_path(:id)%>
	</li> <br/>

<% end %>
</ul>


		<div class="clear"></div>
	</div>

</main>

app/views/event/_success.html.erb
<p> Your event has been created! </p>

app/views/event/create.js.erb
console.log("triggered");

$('#event_create').append("<%= j(render template: 'event/_success')%>");

app/views/event/index.html.erb
<ul>
<% @events.each do |event| %>
<li class="events" data-latitude="<%=event.lat%>" data-longitude="<%=event.lng%>">


	<%= event.name %> <%= event.event_type %> <%= event.date %>
	
	<%=link_to 'Edit', edit_event_path(:id)%>
	
	<%=link_to 'Show', event_path(:id)%>
	</li>

<% end %>
</ul>

<div id="map"> </div>

app/views/event/new.html.erb
<div class="event_form">

	<%= form_for @event, :remote => true, :url => event_index_path do |e| %>
		<%= field_set_tag do %>
			<%= e.label :name %>
			<%= e.text_field :name %>
		<% end %>

		<%= field_set_tag do %>
			<%= e.label :event_type %>
			<%= e.text_field :event_type %>
		<%end %>

		<%= field_set_tag do %>
			<%= e.label :address %>
			<%= e.text_field :address %>
		<% end %>

		<%= field_set_tag do %>
			<%= e.label :description %>
			<%= e.text_field :description %>
		<% end %>

		<%= field_set_tag do %>
			<%= e.label :date %>
			<%= e.text_field :date %>
		<% end %>

		<%= field_set_tag do %>
			<%= e.label :start_time %>
			<%= e.text_field :start_time %>
		<% end %>

		<%= field_set_tag do %>
			<%= e.label :end_time %>
			<%= e.text_field :end_time %>
		<% end %>

		<%= field_set_tag do %>
			<%= e.hidden_field :church_id %>
		<% end %>

		<%= e.submit %>
	<% end %> 
</div>

app/views/event/new.js.erb
// console.log("hello");

var html = "<%= j(render template: 'event/new.html') %>";


$("#event_create").html(html);

app/views/event_attendee/create.js.erb
$("#my_event_list").append("<li> <%= @attendence.event.name%></li>");
$("#attend").removeAttr("data-disable-with");

app/views/home/index.html.erb
<nav id="nav">
  <ul id="login_nav">
    <li id="one"> <%= link_to "Church Login", new_pastor_registration_path %> </li>
    <li id="two"> <%= link_to "Login with Facebook", authorise_fb_attendee_index_path %> </li>
  </ul>
</nav>


<h1 id="title"> findA </h1>
<p id="tagline"> The app for finding Adventist churches and events, all in one place. </p> 
<div class="clear"></div>

<section id="footer">
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FindA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDsB45NGPF2KU_6CE_d4ec9jNNA9tEP5yE">
    </script>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:700|Signika:400,700|Nunito:400,700' rel='stylesheet' type='text/css'>
</head>
<body>

<main class="main">

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

<div class="wrapper">
<%= yield %>
</div>

</main>
</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FindA</title>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=PT+Serif|Raleway' rel='stylesheet' type='text/css'>
</head>

<body>
	<nav class="nav_2">
		<ul>
			<li>Events</li>
			<li>Churches</li>
			<li>Sign Out</li>
		</ul>
	</nav>


<%= yield %>

</body>
</html>

app/views/search/index.html.erb
<h2 class="search_results"> Search Results </h2>

<div id='search_field'>
	<%= form_tag(search_index_path, :method => :get) do %>
		<div class="search_button">
	 		<%= label_tag(:location, "Search:") %>
		</div>
	  <%= text_field_tag(:location) %>
	  <%= submit_tag("Search") %>
	<% end %>
</div>
	
<div id="local_churches">
	<% @search_ch.each do |church| %>
		<ul>
			<div class="church_info">
				<li class="church_name"><%= church.name %> </li> <br/>
				<li class="church_add"><%= church.address %></li>
			</div>
		</ul>
	<%end%>
</div>

<div id="local_events">
	<% @search_ev.each do |event| %>
		<ul>
			<div class="event_info">
				<li class="event_name"><%= event.name %> </li> <br/>
				<li class="event_add"><%= event.address %></li>
				<li class="event_date"><%= event.date %></li>
				<li class="start"><%= event.start_time %></li>
				<li class="end"><%= event.end_time %></li>
				<li class="event_type"><%= event.event_type %></li>
			</div>
		</ul>
	<%end%>
</div>

<div id="map"> </div>
<div class="clear"></div>